# Generated by Django 5.2.15 on 2026-06-10 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=512, null=True)),
                ('tax_number', models.CharField(blank=True, help_text='VAT registration number (e.g. ZATCA 15-digit)', max_length=100, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_with_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('match', 'Match'), ('mismatch', 'Mismatch'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('validation_delta', models.DecimalField(blank=True, decimal_places=2, help_text='table_total - qr_total; 0.00 = perfect match', max_digits=14, null=True)),
                ('original_file_name', models.CharField(blank=True, max_length=512)),
                ('invoice_timestamp', models.DateTimeField(blank=True, help_text='Date/time printed on the invoice', null=True)),
                ('raw_gemini_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=512)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Line Item',
                'verbose_name_plural': 'Line Items',
                'db_table': 'invoice_line_items',
            },
        ),
    ]
